#https://www.youtube.com/watch?v=ON6etBHqf10
version: "3.8"
services:

  django:
    build: .
    ports:
      - 8087:8000
    volumes:
      - ./usuarios:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ${pwd}/local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: calebji@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ${pwd}pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata: {}
  pgadmin-data: {}